deployment:
  name: webapp-deployment
  replicaCount: 3

image:
  repository: gituser-poo/useraccount:1
  pullPolicy: Always
  containerName: useraccount
  imagePullSecrets: dockerhub
  containerPort: 3080
  
service:
  type: ClusterIP
  clusterIPPort: 80